print("Letz go!")
require("hj.keymaps")
require("hj.options")
require("hj.packer")
require("hj.lsp")
require("hj.null-ls")
require("hj.colorscheme")
require("hj.cmp")
require("hj.autopairs")
require("hj.bufferline")
require("hj.alpha")
require("hj.project")
require("hj.whichkey")
require("hj.impatient")
require("hj.nvim-tree")
